services:
  - type: web
    name: car-inventory-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_SHEETS_SPREADSHEET_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: ./credentials/google-credentials.json
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_ISSUER
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: CORS_ORIGIN
        sync: false
      - key: LOG_LEVEL
        value: info
